name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub Actor
        run: echo "This workflow was triggered by ${{ github.actor }}"

      # 2. Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 6. Build and Push the Docker Image for all services
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ignacio-backend:latest
            ghcr.io/${{ github.repository_owner }}/ignacio-backend:${{ github.sha }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ignacio-frontend:latest
            ghcr.io/${{ github.repository_owner }}/ignacio-frontend:${{ github.sha }}


      # 5. Confirm Success
      - name: Verify Image
        run: |
          echo "Docker image has been pushed to:"
          echo "ghcr.io/${{ github.repository_owner }}/ignacio-backend:latest"
          echo "ghcr.io/${{ github.repository_owner }}/ignacio-backend:${{ github.sha }}"
          echo "ghcr.io/${{ github.repository_owner }}/ignacio-frontend:latest"
          echo "ghcr.io/${{ github.repository_owner }}/ignacio-frontend:${{ github.sha }}"